apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamlit-app-data
  namespace: llmsearchindex
  labels:
    app.kubernetes.io/name: streamlit-app
    app.kubernetes.io/part-of: llmsearchindex
    app.kubernetes.io/managed-by: autopoc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
