apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
  namespace: llmsearchindex
  labels:
    app.kubernetes.io/name: streamlit-app
    app.kubernetes.io/part-of: llmsearchindex
    app.kubernetes.io/managed-by: autopoc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: streamlit-app
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
